(fx complex-fx (x: Int y: Int) (-> Int)
  (let (z (* x y))
    (let (result (if (> z 10)
                     (let (doubled (* z 2))
                       doubled)
                     (let (tripled (* z 3))
                       tripled)))
      (+ result 5))))

(print "fx complex-fx: " (complex-fx 5))