import { take, range } from "/Users/seoksoonjang/Desktop/hql/Users/seoksoonjang/Desktop/hql/core/lib/stdlib/stdlib.ts";
console.log("First 5 elements from infinite range:");
console.log(take(5, range()));
console.log("\\nRange with end only:");
console.log(take(5, range(10)));
console.log("\\nRange with start and end:");
console.log(take(5, range(5, 15)));
console.log("\\nRange with start, end, and step:");
console.log(take(5, range(0, 20, 4)));
console.log("\\nRange with negative step:");
console.log(take(5, range(10, -10, -2)));
console.log("\\nFirst 5 numbers after 10000:");
console.log(take(5, range(10000, Infinity)));
